# Generated by Django 4.2.7 on 2023-11-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0002_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
