# Generated by Django 4.2.7 on 2023-11-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
    ]
