# Generated by Django 4.2.7 on 2023-11-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0005_rename_user_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
